"""Opt-in spectral-path worker state; the original CacheTune path is untouched.

Chunk statistics stay sharded until the driver sums squared norms over TP
workers.  Summing norms after sqrt would give a different token ranking.
"""
import math
import statistics
import tempfile
import time
from pathlib import Path
from types import MethodType
from typing import Any, Dict, List, Optional

import torch


def low_band_squared_norm(raw: torch.Tensor, alpha: float = 0.5) -> torch.Tensor:
    """Squared norm per token of the low-pass reconstruction, local TP heads.

The token axis is transformed independently for each channel. Keep exactly
floor(alpha * (floor(T / 2) + 1)) rFFT bins, including the DC bin when nonzero.
K must be the pre-RoPE tensor collected by the model's existing hook.
    """
    if raw.ndim < 2 or raw.shape[0] == 0:
        raise ValueError("Expected nonempty [tokens, ...channels] raw KV")
    if not 0.0 <= alpha <= 1.0:
        raise ValueError("alpha must lie in [0, 1]")
    x = raw.detach().float()
    spectrum = torch.fft.rfft(x, dim=0)
    cutoff = math.floor(alpha * spectrum.shape[0])
    spectrum[cutoff:] = 0
    low = torch.fft.irfft(spectrum, n=x.shape[0], dim=0)
    return low.flatten(1).square().sum(dim=1).cpu()


def _pin(tensor: torch.Tensor) -> torch.Tensor:
    return tensor.detach().to("cpu").contiguous().pin_memory()


def _load_tensor(path: str) -> torch.Tensor:
    # Files are generated by this worker, never supplied external checkpoints.
    return torch.load(path, map_location="cpu")


def _install_disk_prefetch(model) -> None:
    """Install an instance-only adapter; inactive calls use original methods."""
    if getattr(model, "_spectral_disk_adapter_installed", False):
        return
    model._spectral_original_prefetch = model._prefetch_layer
    model._spectral_original_rebuild = model._rebuild_old_kv
    model._spectral_disk_cpu_buffers = {}

    def prefetch(self, layer_idx):
        meta = self.cache_fuse_metadata
        if not meta.get("spectral_disk_enabled", False):
            return self._spectral_original_prefetch(layer_idx)
        paths = meta["spectral_disk_paths"]
        shapes = meta["spectral_disk_shapes"]
        if not 0 <= layer_idx < len(paths):
            return
        shape, dtype = shapes[layer_idx]
        if layer_idx in meta["check_layers"]:
            with torch.cuda.stream(self._transfer_stream):
                self._transfer_events[layer_idx].record(self._transfer_stream)
            self._prefetch_buffers[layer_idx] = (
                "zero", shape[0], shape[1:], dtype)
            return
        cpu_k = _pin(_load_tensor(paths[layer_idx][0]))
        cpu_v = _pin(_load_tensor(paths[layer_idx][1]))
        with torch.cuda.stream(self._transfer_stream):
            k_gpu = cpu_k.to("cuda", non_blocking=True)
            v_gpu = cpu_v.to("cuda", non_blocking=True)
            self._transfer_events[layer_idx].record(self._transfer_stream)
        # Keep pinned buffers alive until their DMA event is complete.
        self._spectral_disk_cpu_buffers[layer_idx] = (cpu_k, cpu_v)
        self._prefetch_buffers[layer_idx] = ("full", k_gpu, v_gpu)

    def rebuild(self, layer_idx):
        self._spectral_original_rebuild(layer_idx)
        self._spectral_disk_cpu_buffers.pop(layer_idx, None)

    model._prefetch_layer = MethodType(prefetch, model)
    model._rebuild_old_kv = MethodType(rebuild, model)
    model._spectral_disk_adapter_installed = True


class CacheTuneSpectralWorkerMixin:
    """Only called by examples that explicitly select --method spectral."""

    def _spectral_model(self):
        return self.model_runner.model.model

    def _spectral_clear_runtime(self) -> None:
        model = self._spectral_model()
        # A completed generate() can leave stream work or cache tensors alive.
        torch.cuda.synchronize()
        meta = model.cache_fuse_metadata
        for name in (
                "cpu_kv_cache", "non_imp_indices", "transfer_indices",
                "reuse_indices", "precomputed_indices", "work_key", "work_val",
                "gpu_transfer_k", "gpu_transfer_v", "disk_kv_cache",
                "disk_kv_meta", "spectral_disk_paths", "spectral_disk_shapes",
                "org_pos", "original_slot_mapping", "our_slot_mapping"):
            meta.pop(name, None)
        meta.update(collect=False, check=False, pipeline_enabled=False,
                    attn_bias=None, imp_indices=None, fake_q=None,
                    layer_counter=0, use_disk_kv_cache=False,
                    spectral_disk_enabled=False, spectral_causal_mask=False)
        model._pipeline_initialized = False
        model._prefetch_buffers = {}
        model.old_kvs = [[None, None] for _ in model.layers]
        if hasattr(model, "_spectral_disk_cpu_buffers"):
            model._spectral_disk_cpu_buffers.clear()
        if hasattr(model, "_cached_sparse_positions"):
            model._cached_sparse_positions = None
        if hasattr(model, "_warmup_prefetched_layer"):
            model._warmup_prefetched_layer = None

    def cachetune_spectral_begin(self, context_id: str = "current") -> None:
        self._spectral_clear_runtime()
        if not hasattr(self, "_spectral_contexts"):
            self._spectral_contexts = {}
        if context_id in self._spectral_contexts:
            self.cachetune_spectral_release(context_id)
        self._spectral_active_context = context_id
        self._spectral_contexts[context_id] = {
            "chunks": [], "full_kv": None, "chunk_lengths": [], "disk": None,
            "suffix_len": None}
        model = self._spectral_model()
        for layer in model.layers:
            layer.self_attn.hack_kv = None
        model.cache_fuse_metadata.update(collect=True, check=False)

    def cachetune_spectral_append_chunk(
            self, start: int, end: int, score: bool = True,
            alpha: float = 0.5) -> Dict[str, Any]:
        """Capture one completed prefill using exact token-ID slice bounds."""
        model = self._spectral_model()
        context = self._spectral_contexts[self._spectral_active_context]
        if context["full_kv"] is not None:
            raise RuntimeError("Cannot append after spectral cache finalization")
        if start < 0 or end <= start:
            raise ValueError("Chunk slice must satisfy 0 <= start < end")
        chunk, k_sq, v_sq, replication = [], [], [], []
        tp_size = self.parallel_config.tensor_parallel_size
        for layer_idx, layer in enumerate(model.layers):
            attn = layer.self_attn
            kv = attn.hack_kv
            if kv is None or len(kv) != 2 or end > kv[0].shape[0]:
                raise RuntimeError(
                    "Missing/short prefill KV at layer %d; use max_tokens=1 "
                    "and exact prompt_token_ids" % layer_idx)
            k = kv[0][start:end].detach()
            v = kv[1][start:end].detach()
            if k.shape != v.shape:
                raise RuntimeError("K/V shape mismatch in collected chunk")
            if score:
                k_sq.append(low_band_squared_norm(k, alpha))
                v_sq.append(low_band_squared_norm(v, alpha))
            # clone ensures these snapshots never alias subsequent hook buffers.
            chunk.append((_pin(k.clone()), _pin(v.clone())))
            replication.append(max(1, tp_size // attn.total_num_kv_heads))
            attn.hack_kv = None
        context["chunks"].append(chunk)
        context["chunk_lengths"].append(end - start)
        result = {"length": end - start,
                  "replication_factor": replication,
                  "num_layers": len(model.layers)}
        if score:
            result.update(k_sq=torch.stack(k_sq), v_sq=torch.stack(v_sq))
        return result

    def cachetune_spectral_finalize(
            self, context_id: str = "current", last_len: int = 0) -> Dict[str, Any]:
        """Seal cached chunks and reserve zero placeholders for the new query.

The suffix is never collected or scored offline. Its placeholder rows only
reserve absolute positions: prepare() requires them all to be recomputed and
never transfers them from CPU or disk.
        """
        context = self._spectral_contexts[context_id]
        model = self._spectral_model()
        if last_len < 0:
            raise ValueError("Suffix length cannot be negative")
        if context["full_kv"] is None:
            if not context["chunks"]:
                raise RuntimeError("Spectral context has no collected chunks")
            if last_len:
                first_chunk = context["chunks"][0]
                context["chunks"].append([
                    tuple(tensor.new_zeros((last_len,) + tensor.shape[1:])
                          for tensor in layer_kv)
                    for layer_kv in first_chunk])
            context["full_kv"] = tuple(
                tuple(_pin(torch.cat([chunk[layer_idx][kind]
                                      for chunk in context["chunks"]], dim=0))
                      for kind in range(2))
                for layer_idx in range(len(model.layers)))
            context["chunks"] = []
            context["suffix_len"] = last_len
        elif context["suffix_len"] != last_len:
            raise ValueError("Cannot change suffix length of a finalized context")
        model.cache_fuse_metadata["collect"] = False
        kv = context["full_kv"]
        attn = model.layers[0].self_attn
        return {"total_len": int(kv[0][0].shape[0]),
                "num_layers": len(kv),
                "local_num_kv_heads": int(attn.num_kv_heads),
                "total_num_kv_heads": int(attn.total_num_kv_heads),
                "head_dim": int(attn.head_dim),
                "element_size": int(kv[0][0].element_size()),
                "suffix_len": context["suffix_len"],
                "chunk_lengths": list(context["chunk_lengths"])}

    def cachetune_spectral_prepare(
            self, final_indices_cpu: torch.Tensor, last_len: int,
            recomp_ratio: float, storage: str = "cpu",
            disk_root: Optional[str] = None,
            check_layers: Optional[List[int]] = None,
            context_id: str = "current") -> Dict[str, Any]:
        """Install a fresh compact cache; keep the full source immutable."""
        context = self._spectral_contexts[context_id]
        full_kv = context["full_kv"]
        if full_kv is None:
            raise RuntimeError("Finalize spectral context before prepare")
        if storage not in ("cpu", "disk"):
            raise ValueError("storage must be cpu or disk")
        if not 0.0 <= recomp_ratio <= 1.0:
            raise ValueError("recomp_ratio must lie in [0, 1]")
        total = full_kv[0][0].shape[0]
        if not 0 < last_len <= total:
            raise ValueError("A nonempty suffix is required")
        if context["suffix_len"] != last_len:
            raise ValueError("Suffix length differs from finalized context")
        selected = torch.as_tensor(final_indices_cpu, dtype=torch.int64,
                                   device="cpu").flatten()
        if (selected.numel() == 0 or selected.min() < 0
                or selected.max() >= total):
            raise ValueError("Spectral recompute indices are empty or out of range")
        if not torch.equal(selected, torch.unique(selected, sorted=True)):
            raise ValueError("Spectral recompute indices must be sorted and unique")
        suffix = torch.arange(total - last_len, total, dtype=torch.int64)
        if not torch.equal(selected[-last_len:], suffix):
            raise ValueError("Every suffix token must be recomputed")
        mask = torch.ones(total, dtype=torch.bool)
        mask[selected] = False
        reused = torch.arange(total, dtype=torch.int64)[mask]
        self._spectral_clear_runtime()
        model = self._spectral_model()
        meta = model.cache_fuse_metadata
        check_layers = [1] if check_layers is None else list(check_layers)
        if (len(check_layers) != 1 or not 0 <= check_layers[0] < len(model.layers)):
            raise ValueError("Spectral path requires one valid check layer")
        if reused.numel() == 0:
            # Full recompute needs no compact KV or empty-tensor RoPE kernels.
            return {"total_len": total, "recompute_tokens": total,
                    "transfer_tokens": 0, "full_prefill": True}
        selected_gpu = selected.to("cuda")
        reused_gpu = reused.to("cuda")
        meta.update(org_seq_len=total, precomputed_indices=[selected_gpu],
                    transfer_indices=reused_gpu, non_imp_indices=reused_gpu)
        # A single selected set is required: hidden states are pruned once at
        # the check layer and cannot grow or change identity in later layers.
        if storage == "cpu":
            meta["cpu_kv_cache"] = [
                [_pin(k[reused]), _pin(v[reused])] for k, v in full_kv]
        else:
            _install_disk_prefetch(model)
            if context["disk"] is None:
                root = Path(disk_root or "disk_offload_cache")
                root.mkdir(parents=True, exist_ok=True)
                context["disk"] = Path(tempfile.mkdtemp(
                    prefix="spectral_rank%d_" % self.rank, dir=str(root)))
            paths, shapes = [], []
            for i, (k, v) in enumerate(full_kv):
                k_path = context["disk"] / ("layer_%d_k.pt" % i)
                v_path = context["disk"] / ("layer_%d_v.pt" % i)
                k_compact, v_compact = k[reused].contiguous(), v[reused].contiguous()
                torch.save(k_compact, str(k_path))
                torch.save(v_compact, str(v_path))
                paths.append((str(k_path), str(v_path)))
                shapes.append((tuple(k_compact.shape), k_compact.dtype))
            meta.update(spectral_disk_enabled=True, spectral_disk_paths=paths,
                        spectral_disk_shapes=shapes,
                        cpu_kv_cache=[None] * len(full_kv))
        attn = model.layers[0].self_attn
        shape = (total, attn.num_kv_heads, attn.head_dim)
        meta.update(work_key=torch.empty(shape, dtype=full_kv[0][0].dtype,
                                         device="cuda"),
                    work_val=torch.empty(shape, dtype=full_kv[0][1].dtype,
                                         device="cuda"),
                    check_layers=check_layers, check=True, collect=False,
                    recomp_ratio=float(recomp_ratio), fast_attention=True,
                    suffix_len=int(last_len), pipeline_enabled=True,
                    layer_counter=0, spectral_causal_mask=True)
        return {"total_len": total, "recompute_tokens": selected.numel(),
                "transfer_tokens": reused.numel(), "full_prefill": False}

    def cachetune_spectral_disable(self) -> None:
        """Run baseline/full prefill while retaining calibration snapshots."""
        self._spectral_clear_runtime()

    def cachetune_spectral_release(self, context_id: Optional[str] = None) -> None:
        self._spectral_clear_runtime()
        contexts = getattr(self, "_spectral_contexts", {})
        keys = list(contexts) if context_id is None else [context_id]
        for key in keys:
            context = contexts.pop(key, None)
            if context is None or context["disk"] is None:
                continue
            # Delete only worker-created files in its unique temporary directory.
            folder = context["disk"]
            for path in folder.glob("layer_*_*.pt"):
                path.unlink()
            folder.rmdir()

    def cachetune_spectral_profile_transfer(
            self, context_id: str = "current", storage: str = "cpu",
            disk_root: Optional[str] = None, trials: int = 3) -> Dict[str, Any]:
        """Measure one full layer's actual load + DMA, excluding file writes.

Disk measurements use the OS's current page-cache state. They are not cold
SSD throughput, and must not be described as such in experiment reports.
        """
        if storage not in ("cpu", "disk") or trials < 1:
            raise ValueError("Invalid transfer profile configuration")
        context = self._spectral_contexts[context_id]
        full_kv = context["full_kv"]
        if full_kv is None:
            raise RuntimeError("Finalize context before profiling")
        k, v = full_kv[min(2, len(full_kv) - 1)]
        context_len = k.shape[0] - context["suffix_len"]
        # Own the sliced storage: torch.save(view) would also serialize its
        # backing allocation, including uncached suffix placeholder rows.
        k, v = _pin(k[:context_len].clone()), _pin(v[:context_len].clone())
        byte_count = k.numel() * k.element_size() + v.numel() * v.element_size()
        elapsed = []
        folder = None
        try:
            if storage == "disk":
                root = Path(disk_root or "disk_offload_cache")
                root.mkdir(parents=True, exist_ok=True)
                folder = Path(tempfile.mkdtemp(prefix="spectral_profile_", dir=str(root)))
                torch.save(k, str(folder / "k.pt"))
                torch.save(v, str(folder / "v.pt"))
            for _ in range(trials):
                torch.cuda.synchronize()
                started = time.perf_counter()
                if folder is None:
                    cpu_k, cpu_v = k, v
                else:
                    cpu_k = _pin(_load_tensor(str(folder / "k.pt")))
                    cpu_v = _pin(_load_tensor(str(folder / "v.pt")))
                gpu_k = cpu_k.to("cuda", non_blocking=True)
                gpu_v = cpu_v.to("cuda", non_blocking=True)
                torch.cuda.synchronize()
                elapsed.append(time.perf_counter() - started)
                del gpu_k, gpu_v
        finally:
            if folder is not None:
                (folder / "k.pt").unlink()
                (folder / "v.pt").unlink()
                folder.rmdir()
        median = statistics.median(elapsed)
        return {"bytes": byte_count, "seconds": median,
                "bytes_per_second": byte_count / median,
                "seconds_per_token_layer": median / context_len,
                "context_tokens": context_len, "measured_layers": 1,
                "storage": storage, "trials": trials,
                "disk_cache_state": "os_managed" if storage == "disk" else None}
